global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'bluetrace-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    
  - job_name: 'bluetrace-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    
  - job_name: 'bluetrace-postgres'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 15s
